name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch name

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        run: |
          cd frontend
          npm ci
          npm install -g @vue/cli

      - name: Build
        run: |
          cd frontend
          # Clean any existing build
          rm -rf dist
          # Install dependencies again to ensure everything is up to date
          npm install
          # Build the project
          npm run build
          # Verify the build output
          echo "Listing contents of dist directory:"
          ls -la dist/
        env:
          NODE_ENV: production
          VITE_BASE_URL: "/Vue-practice/"

      - name: Debug - List all files
        run: |
          echo "Current directory structure:"
          pwd
          ls -la
          echo "Frontend directory structure:"
          ls -la frontend/
          echo "Dist directory structure:"
          ls -la frontend/dist/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/dist
          branch: gh-pages
          clean: true
          commit-message: "Deploy Vue.js application"
